spring:
   application:
      name: userMicroservice
   mail:
      host: smtp.gmail.com
      port: 587
      username: manuexcd
      password: vnhfonbmhfilsfac
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
                  required: true
   jpa:
      database: mysql
      hibernate:
         ddl-auto: update
         dialect: org.hibernate.dialect.MySQL5Dialect
   datasource:
      url: jdbc:mysql://localhost:3306/user_microservice?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: tfg
      password: tfg
server:
   port: 8080
google:
   bucket-name: "tfg-images-gcp"
   credentials:
      path: "src/main/resources/google-credentials.json"
      