spring:
   application:
      name: tfg
   mail:
      host: smtp.gmail.com
      port: 587
      username: manuexcd
      password: vnhfonbmhfilsfac
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
                  required: true
   jpa:
#show-sql: true
      database: mysql
      hibernate:
         ddl-auto: update
         dialect: org.hibernate.dialect.MySQL5Dialect
   datasource:
      url: jdbc:mysql://localhost:3306/userMicroservice?autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: tfg
      password: tfg