name: build
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.0
        with:
          java-version: 8
          distribution: zulu
      - name: Setup Maven
        run: sudo apt install maven
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: Build docker image
        run: mvn clean package --quiet
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
          file: Dockerfile
          context: ../target
